services:
  spamassassin:
    image: axllent/spamassassin
    ports:
      - "783:783"
    restart: always
    environment:
      - DNS_CHECKS=1
    volumes:
      - spamassassin_data:/var/lib/spamassassin

volumes:
  spamassassin_data: {}
